In [1]:
import numpy as np

## numpy array

In [2]:
#numpy dizisi
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem) #numpy bunu diziye çeviriyor

array([20, 30, 40])

In [5]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [6]:
type(matrixListesi)

list

In [7]:
matrixListesi[1]

[20, 30, 40]

In [8]:
matrixListesi[1][0]

20

In [9]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# methodlar   arange

In [10]:
range(0,10)

range(0, 10)

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10) #diziyi oluşturuyor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2) #2 stepsize 2 de bir atla ve son karakteri almıyor 

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0,20,2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros

In [15]:
np.zeros(5) #içerisinde 5 tane 0 olan diziyi oluşturuyor

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((9,9)) #ayrı parantezin içinde yazmalısın

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones(5) #5 tane 1 den oluşuyor

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace

In [20]:
np.linspace(0,20,5) #belirttiğimiz numaralar arasında boyutlandırılmış eşit aralıklarla bir dizi oluşturuyor
#0 dan başlayıp 20 ye kadar 5 veri seti(5 mesafe var)

array([ 0.,  5., 10., 15., 20.])

In [21]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [22]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# eye

In [23]:
#matrix oluşturuyor
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

In [26]:
np.random.randn(4)

array([ 0.23808371,  0.60450073, -0.59059582,  0.50547501])

In [27]:
np.random.randn(4,4)

array([[-1.35039328,  1.05255275, -0.78997908,  1.2574519 ],
       [ 1.16547619,  2.31081831,  1.03197871,  0.91208857],
       [-0.30637123,  2.5332609 ,  1.06740274, -0.54041932],
       [-0.28865412, -1.18470712,  2.15631754,  0.24248273]])

In [29]:
np.random.randint(1,10) #son rakamı almıyor!

5

In [30]:
np.random.randint(1,10,5)#sondaki kaç rakam istediğimizi söyler
#rastgele rakamları atıyor 

array([7, 6, 7, 2, 5])

In [31]:
benimNumpyDizim=np.arange(30)

In [32]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
benimRandomDizim=np.random.randint(0,100,30)

In [34]:
benimRandomDizim

array([33, 61, 46,  9, 78,  5, 70, 70, 82,  3, 95, 57, 41, 74, 19, 58, 72,
       42, 42, 59, 87, 96,  9, 84, 18, 13, 10, 31, 92, 48])

# numpy dizi methodları

In [35]:
benimNumpyDizim.reshape(5,6) #5 satır(column) 6 sütun(row)
#reshape, yeniden şekillendir

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
benimNumpyDizim.max()

29

In [37]:
benimRandomDizim.max()

96

In [38]:
#argmax kaçıncı indexin büyük olduğunu bize söyler
benimRandomDizim.argmax()

21

In [39]:
benimRandomDizim.min() #en küçüğünü gösteriyor

3

In [40]:
benimRandomDizim.argmin() #indexini gösteriyor

9

In [41]:
benimNumpyDizim.shape #shape metod değil bir özellik o yüzden sona parantez koymadık

(30,)

In [42]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
reshapeDizim=benimNumpyDizim.reshape(5,6)

In [46]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [47]:
reshapeDizim.shape #güncel dizimin hangi şekle sahip olduğunu bu şekilde alabilirim

(5, 6)