In [1]:
import numpy as np

In [2]:
benimDizim=np.arange(0,15) #bir dizi oluşturmasını istiyoruz

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5] #5. index gelir NOT:indexler 0 dan başlar

5

In [5]:
benimDizim[3:5] #3.indexten başlıyor belirttiğmiz sona kadar devam ediyor ama sonuncusunu almıyor.

array([3, 4])

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
#negatif sayıları da istiyoruz
benimDizim[3:8]=-5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi=np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicingDizisi=baskaDizi[4:9]

In [12]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [13]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingDizisi[:]=700 #hepsi 700 olur

In [16]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [17]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [19]:
ornekDizi=np.arange(0,24)

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyasi=ornekDizi.copy()

In [22]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
ornekDiziKopyaSlicing=ornekDiziKopyasi[3:6]

In [28]:
ornekDiziKopyaSlicing

array([3, 4, 5])

In [29]:
ornekDiziKopyaSlicing[:]=800

In [30]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [31]:
ornekDiziKopyasi #800 ler belirttiğimiz araya geldiler

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [32]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# matrix indexler

In [34]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [35]:
benimMatrixDizim=np.array(benimListem)

In [36]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [37]:
benimMatrixDizim[0]

array([10, 20, 30])

In [38]:
benimMatrixDizim[1][2]

40

In [39]:
benimMatrixDizim[1,2]

40

In [40]:
benimMatrixDizim[1:,2]

array([40, 60])

In [41]:
benimMatrixDizim[0:,2]

array([30, 40, 60])

In [42]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [43]:
yeniMatrix=np.array(yeniListe)

In [46]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
yeniMatrix[[0,2,4]] #0-2-4.indexleri alıp getiriyor

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [49]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

# operasyonlar

In [54]:
yeniBirDizi=np.random.randint(1,100,20)

In [55]:
yeniBirDizi

array([ 9, 18, 60, 81, 53, 85, 84,  1, 41, 81, 96, 33, 39, 39, 51, 28, 99,
       13, 59, 78])

In [56]:
yeniBirDizi>24

array([False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True])

In [57]:
yeniBirDizi

array([ 9, 18, 60, 81, 53, 85, 84,  1, 41, 81, 96, 33, 39, 39, 51, 28, 99,
       13, 59, 78])

In [58]:
sonucDizisi=yeniBirDizi>24

In [59]:
sonucDizisi

array([False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True])

In [61]:
yeniBirDizi

array([ 9, 18, 60, 81, 53, 85, 84,  1, 41, 81, 96, 33, 39, 39, 51, 28, 99,
       13, 59, 78])

In [63]:
yeniBirDizi[sonucDizisi]

array([60, 81, 53, 85, 84, 41, 81, 96, 33, 39, 39, 51, 28, 99, 59, 78])

In [65]:
yeniBirDizi[yeniBirDizi>24]

array([60, 81, 53, 85, 84, 41, 81, 96, 33, 39, 39, 51, 28, 99, 59, 78])

In [66]:
sonDizi=np.arange(0,24)

In [67]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [69]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [70]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [71]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [73]:
np.max(sonDizi)

23

In [74]:
np.min(sonDizi)

0